version: "3.7"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./packages/backend/.env

  backend:
    container_name: backend_container
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
    volumes:
      - ./packages/backend/src:/usr/application/src
    depends_on:
      - postgres

  frontend:
    container_name: frontend_container
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./packages/frontend/.env
    volumes:
      - ./packages/frontend/src:/usr/application/src
    depends_on:
      - backend
