#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


cd packages
cd frontend; yarn lint:tsc; yarn test --bail; yarn lint-staged; cd ../
cd backend; yarn lint:tsc; yarn test --bail; yarn lint-staged; cd ../
cd ../
